Update PasskeyRegistryModule generate userOp test case
bcnmy/scw-contracts pull request #183
Opened 2023-12-12 06:19 UTC by AmanRaj1608

- Updated the `isValidSignature` to add the EIP-1271 Replay fix
- Add generate userOp example for passkeys

2023-12-13 22:14 UTC, livingrockrises approved these changes

2023-12-22 00:45 UTC, Aboudjem requested changes

2023-12-22 00:45 UTC, Aboudjem commented on contracts/smart-account/modules/PasskeyRegistryModule.sol
> +    mapping(address => PassKeyId) public _smartAccountPasskey;
`_` according to solidity best practices and guidelines should be used only for `private` and `internal` variables / functions

2023-12-22 00:45 UTC, Aboudjem commented on contracts/smart-account/modules/PasskeyRegistryModule.sol
> +     * @dev Returns the owner of the Smart Account. Reverts for Smart Accounts without owners.
I think it's not reverting here

2023-12-26 09:52 UTC, ankurdubey521 approved these changes

2024-01-02 13:55 UTC, merged